/*
 * kbdKeymap.h
 *
 *  Created on: May 28, 2021
 *      Author: Anthony
 */

#ifndef SRC_KBDMATRIXREAD_KBDKEYMAP_H_
#define SRC_KBDMATRIXREAD_KBDKEYMAP_H_

#include "stm32f1xx_hal.h"
#include "usb_keycode.h"
#include "kbdLayout.h"




const uint16_t keymap_azerty[][MATRIX_COLS][MATRIX_ROWS] = {
    LAYOUT(\
        KEY_ESC, 		KEY_1,			KEY_2,		KEY_3,   KEY_4,   KEY_5,   KEY_6,   KEY_7,   KEY_8,   KEY_9,   		KEY_0,   		KEY_MINUS,		KEY_EQUAL, 		KEY_BACKSPACE,\
		KEY_TAB, 		KEY_Q,			KEY_W,		KEY_E,   KEY_R,   KEY_T,   KEY_Y,   KEY_U,   KEY_I,   KEY_O,   		KEY_P,   		KEY_LEFTBRACE,	KEY_RIGHTBRACE, KEY_ENTER,\
		KEY_CAPSLOCK, 	KEY_A,			KEY_S,		KEY_D,   KEY_F,   KEY_G,   KEY_H,   KEY_J,   KEY_K,   KEY_L,   		KEY_SEMICOLON,  KEY_APOSTROPHE,	KEY_HASHTILDE, 	KEY_ENTER,\
		KEY_LEFTSHIFT, 	KEY_BACKSLASH,	KEY_Z,		KEY_X,   KEY_C,   KEY_V,   KEY_B,   KEY_N,   KEY_M,   KEY_COMMA,	KEY_DOT,   		KEY_SLASH,		KEY_UP, 		KEY_RIGHTSHIFT,\
		KEY_LEFTCTRL, 	KEY_LEFTMETA,		KEY_LEFTALT,KEY_3,   KEY_4,   KBD_LAYOUT_DOWN,       KEY_SPACE,    KBD_LAYOUT_UP,   KEY_RIGHTALT,   		KEY_RIGHTCTRL,   		KEY_LEFT,		KEY_DOWN, 		KEY_RIGHT \
    ),

    LAYOUT(\
        KEY_ESC, 		KEY_F1,			KEY_F2,		KEY_F3,  KEY_F4,  KEY_F5,  KEY_F6,  KEY_F7,  KEY_F9,  KEY_F9,  		KEY_F10,   		KEY_F11,		KEY_F12, 		KEY_BACKSPACE,\
		KEY_TAB, 		KEY_Q,			KEY_W,		KEY_E,   KEY_R,   KEY_T,   KEY_Y,   KEY_U,   KEY_I,   KEY_O,   		KEY_P,   		KEY_LEFTBRACE,	KEY_RIGHTBRACE, KEY_ENTER,\
		KEY_CAPSLOCK, 	KEY_A,			KEY_S,		KEY_D,   KEY_F,   KEY_G,   KEY_H,   KEY_J,   KEY_K,   KEY_L,   		KEY_SEMICOLON,  KEY_APOSTROPHE,	KEY_HASHTILDE, 	KEY_ENTER,\
		KEY_LEFTSHIFT, 	KEY_BACKSLASH,	KEY_Z,		KEY_X,   KEY_C,   KEY_V,   KEY_B,   KEY_N,   KEY_M,   KEY_COMMA,	KEY_DOT,   		KEY_SLASH,		KEY_UP, 		KEY_RIGHTSHIFT,\
		KEY_LEFTCTRL, 	KEY_LEFTMETA,		KEY_LEFTALT,KEY_3,   KEY_4,   KBD_LAYOUT_DOWN,       KEY_SPACE,    KBD_LAYOUT_UP,   KEY_RIGHTALT,   		KEY_RIGHTCTRL,   		KEY_LEFT,		KEY_DOWN, 		KEY_RIGHT \
    ),

    LAYOUT(\
        KEY_ESC, 		KEY_F1,			KEY_F2,		KEY_F3,  KEY_F4,  KEY_F5,  KEY_F6,  KEY_F7,  KEY_NUMLOCK,  KEY_KPSLASH,  KEY_KPASTERISK,   	KEY_KPMINUS,		KEY_F12, 		KEY_BACKSPACE,\
		KEY_TAB, 		KEY_Q,			KEY_W,		KEY_E,   KEY_R,   KEY_T,   KEY_Y,   KEY_U,   KEY_KP7,   KEY_KP8,   	KEY_KP9,   		KEY_KPPLUS,	KEY_RIGHTBRACE, KEY_ENTER,\
		KEY_CAPSLOCK, 	KEY_A,			KEY_S,		KEY_D,   KEY_F,   KEY_G,   KEY_H,   KEY_J,   KEY_KP4,   KEY_KP5,   	KEY_KP6,  KEY_KPPLUS,	KEY_HASHTILDE, 	KEY_ENTER,\
		KEY_LEFTSHIFT, 	KEY_BACKSLASH,	KEY_Z,		KEY_X,   KEY_C,   KEY_V,   KEY_B,   KEY_N,   KEY_KP1,   KEY_KP2,	KEY_KP3,   		KEY_ENTER,		KEY_UP, 		KEY_RIGHTSHIFT,\
		KEY_LEFTCTRL, 	KEY_LEFTMETA,		KEY_LEFTALT,KEY_3,   KEY_4,   KBD_LAYOUT_DOWN,       KEY_SPACE,    KBD_LAYOUT_UP,   KEY_KP0,   		KEY_KPDOT,   		KEY_LEFT,		KEY_DOWN, 		KEY_RIGHT \
    )


};


#endif /* SRC_KBDMATRIXREAD_KBDKEYMAP_H_ */
